### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by weijia-cheng** [ConcaveTrillion/marie-belloc-lowndes_the-lodger#1]
- [x] [56012a1d5b2c9068985337fa33fb4998bd760e48](https://github.com/ConcaveTrillion/marie-belloc-lowndes_the-lodger/commit/56012a1d5b2c9068985337fa33fb4998bd760e48) shouldn't be marked as an `[Editorial]` commit, since it isn't changing the actual source text (just how we choose to render a certain semantic type). I like how Vince summarized what constitutes an `[Editorial]` commit in [this post](https://groups.google.com/g/standardebooks/c/CJhAGqN5U2M/m/FIJmlKUpBAAJ). This should be a simple interactive-rebase + rename, but please feel free to ask if you need more specific instructions.
- [x] We have two instances where "for ever so long" became "forever so long" during spelling modernization, which should be changed back.
- [x] The `newspaper` class is superfluous. This would not be a case where we would want to add a custom class (we only do this in very rare occasions). You should remove all instances of the `newspaper` class and replace your newspaper CSS with the CSS from [7.2.10.8](https://standardebooks.org/manual/1.6.4/7-high-level-structural-patterns#7.2.10.8), which covers the usage in this book.
- [x] You gave this the `Drama` SE subject in the metadata but we use that subject to mean plays. We wouldn't use that here.

**Comment by ConcaveTrillion** [comment]
Will rebase and fix. I had searched the email archives and there's many
books with class='newspaper', but I can remove it.

**Comment by weijia-cheng** [comment]
Searching in the organization, I do see many instances of the `newspaper` class, but the past usage seems wrong too! I'm going to put in some PRs to standardize those.

**Comment by ConcaveTrillion** [comment]
- Rebased and corrected [56012a1d5b2c9068985337fa33fb4998bd760e48](https://github.com/ConcaveTrillion/marie-belloc-lowndes_the-lodger/commit/56012a1d5b2c9068985337fa33fb4998bd760e48)
- During rebase also corrected 'for ever so long'
- Removed newspaper class and replaced with the CSS in the manual.
- Removed Drama subject, replaced with Fiction

**Comment by weijia-cheng** [comment]
Ok, the changes look good, just run `clean` one more time since you accidentally removed the trailing newline at the end of the CSS.
