### ISSUE TITLE
Some more issues I noticed

### ISSUE THREAD

**Issue by weijia-cheng** [ConcaveTrillion/marie-belloc-lowndes_the-lodger#2]
- [x] You need to run `clean` one more time since you removed the trailing newline at the end of the CSS.
- [x] In chapter 8, the `<b>` around the "Wanted" header is superfluous with the default header CSS.
- [x] In chapter 11, the blockquote with "Pardon to Accomplices" should be combined with the subsequent blockquote "Dear Sir, etc." since they are the same blockquote.

**Comment by ConcaveTrillion** [comment]
Corrected and pushed!
